name: "test-action"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    name: Action Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Firmware
        uses: ./
        with:
          keymap-path: "keyboards/preonic/keymaps/addy"
          keyboard: "preonic/rev3"
          keymap: "addy"
      - name: Upload a Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build
